### ISSUE TITLE
v1.0.0 Roadmap

### ISSUE THREAD

**Issue by arronhunt** [arronhunt/react-native-emoji-selector#49]
Hey everyone! 

I just wanted to give a shoutout to everyone who has used this library and given feedback. It has been awesome engaging with the OSS community and building a tool that many people are using. This library has been in v0.X since it was originally published, mostly due to my fear of committing to a big 1.0 release. Now that my full-time work has moved to a comfortable cadence and covid lockdowns lightening back up, I have found a new sense of motivation to get a 1.0 release shipped. 

----
## What's changing?
A goal of this library has always been to ship something super lightweight, performant, and with few dependencies. Those goals will remain intact for v1.0. It is also to be opinionated enough that anyone should be able to drop in the `<EmojiSelector />` component and not have to worry about state management or styling.  This will mostly remain the same; however, there have been so many requests for more granular control over design and themeing that I need to make a change. v1.0 will allow you to override 100% of its base-level components. I think this will give some much-needed customization to those who are using this library in their own app who want to maintain control over branding and experience. 

You can follow the progress in the new [`feature/v1`](https://github.com/arronhunt/react-native-emoji-selector/tree/feature/v1) branch.

### Dark mode
Dark mode will work out-of-the-box with no changes needed from v0.2.0. 

![May-07-2021 14-46-54](https://user-images.githubusercontent.com/298336/117511757-24ccc000-af43-11eb-9d87-28635d7e77f6.gif)
_Current progress on dynamic dark/light mode_

### Fully customizable
Every sub-component will support style overrides via the `overrideStyles` prop. 

<img width="547" alt="image" src="https://user-images.githubusercontent.com/298336/117512765-1ed7de80-af45-11eb-88b8-723c7145bfd5.png">

### Limit tab categories. 
The tab bar can be customized to show a limited number of categories.

<img width="577" alt="image" src="https://user-images.githubusercontent.com/298336/117513672-12ed1c00-af47-11eb-8dec-2c9a290a2697.png">

## ☑️ TODO

- [x] Native support for dark mode. [#37]
- [x] Custom themeing and style overrides. [#48]
- [ ] Improved control over emoji categories. [#35]
- [ ] Better rendering performance. [#4]
- [x] Upgrade to use React hooks under the hood.
- [ ] Improve branding and documentation.

## When will it be available?
There are no guarantees. I will need some help from the community to test on multiple versions and devices (especially Android). I will hopefully have a `-beta.0` release out next week to start gathering feedback!

**Comment by emilstepanian** [comment]
Hi @arronhunt, 

Big fan of your package!

Did you stop working on this release?
